lang = {
    direction: 'ltr',
    pageTitle: 'Magiclass Reports System',
    footext: '(c) 2009 - Magiclass ltd.',
    allClasses: 'All Classes',
    studentReportChooserShowBtn: 'Switch Student',
    studNumOfMissesLabel: 'Missed',
    studNumOfActivitiesLabel: 'out of',
    studPostActivitiesLabel: 'Magiclass activities',

    months: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
	days: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    dateFormat: 'mm/dd/yy',
    firstDay: '2',
    dateClose: 'Close',
    dateToday: 'Today',
    next: 'next',
    prev: 'prev',
    studentReport: 'Student',
    dailyReport: 'Daily report - entire school',
    idNum: 'ID',
    studName: 'Name',
    lessonName: 'Lesson',
    clasName: 'Class',
    missAt: 'Missed lessons at',
    missSince: 'Missed lessons since',

    attendance: 'Attendance',
    presentations: 'Presentations',
    tests: 'Tests',
    feedback: 'Feedback',
    resetFilter: 'Reset Filter',
    missingToday: 'Missing Today',
    missingThisWeek: 'Missing This Week',
    byArrival: 'Arrival',
    byLesson: 'Lesson',
    bySince: 'Since',
    byUntil: 'Until',
    byClass: 'Class',
    byStudent: 'Students',
    date: 'Date',
    lesson: 'Lesson',
    cls: 'Class',
    student: 'Student'
}    
