lang = {
    direction: 'rtl',
    title: 'מערכת דו"חות נוכחות',
    footext: '(c) - מאג\'יקלאס בע"מ',
    months: ['ינואר', 'פברואר', 'מרץ', 'אפריל', 'מאי', 'יוני', 'יולי', 'אוגוסט', 'ספטמבר', 'אוקטובר', 'נובמבר', 'דצמבר'],
	days: ['א', 'ב', 'ג', 'ד', 'ה', 'ו', 'ש'],
    dateFormat: 'dd/mm/yy',
    firstDay: '1',
    dateClose: 'סגור',
    dateToday: 'היום',
    next: 'הבא',
    prev: 'הקודם',
    dailyReport: 'דו"ח יומי - כלל בית-ספרי',
    idNum: 'מס\' ת"ז',
    studName: 'שם',
    lessonName: 'שעור',
    clasName: 'כיתה',
    missAt: 'העדרויות ב-',
    missSince: 'העדרויות מ-',

    attendance: 'נוכחות',
    presentations: 'מצגות',
    tests: 'מבחנים',
    feedback: 'משוב',
    resetFilter: 'אפס סינון',
    missingToday: 'נעדרים היום',
    missingThisWeek: 'נעדרים השבוע',
    byArrival: 'נוכחים, נעדרים או שניהם',
    byLesson: 'שעורים',
    bySince: 'מתאריך',
    byUntil: 'עד תאריך',
    byClass: 'כתות',
    byStudent: 'תלמידים',
    date: 'תאריך',
    lesson: 'שעור',
    cls: 'כתה',
    student: 'תלמיד'
}    
